name = "NCTSSOS"
uuid = "74af9cd0-d9b7-11ea-3577-f378dad115d4"
authors = ["jwang <wangjie212@amss.ac.cn>"]
version = "0.4.3"

[deps]
COSMO = "1e616198-aa4e-51ec-90a2-23f7fbd31d8d"
ChordalGraph = "60fd0770-a5cf-11ea-07c5-d789f1eae5cb"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
COSMO = "0.8"
ChordalGraph = "0.4"
DynamicPolynomials = "0.4.6"
MultivariatePolynomials = "< 0.5.0"
Graphs = "1.5"
MetaGraphs = "0.7, 0.8"
JuMP = "1"
MosekTools = "< 0.15.2, 0.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
